apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/onboard-n4k-argo.git
    targetRevision: g-argo-v1.11.4
    path: v1.11/nirmata-kyverno-operator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nirmata-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: webhook-server-cert
      namespace: nirmata-system
      jsonPointers:
        - /data
        - /metadata/resourceVersion
        - /metadata/annotations
        - /data/tls.crt
        - /data/tls.key
        - /data/ca.crt
    - group: security.nirmata.io
      kind: KyvernoConfig
      namespace: nirmata-system
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/generation
        - /status
    - group: security.nirmata.io
      kind: PolicySet
      namespace: nirmata-system
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/generation
        - /status
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: kyverno-operator-validating-webhook-configuration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/generation
    - group: apps
      kind: Deployment
      namespace: nirmata-system
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/generation
        - /status
    - group: apps
      kind: Deployment
      namespace: kyverno
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /metadata/generation
        - /status
    - group: ""
      kind: ServiceAccount
      namespace: nirmata-system
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /secrets
    - group: ""
      kind: ServiceAccount
      namespace: kyverno
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
        - /secrets
