apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - kyverno-app.yaml
  # Add more ArgoCD applications here as needed
  # - nirmata-kyverno-operator-app.yaml
  # - nirmata-kube-controller-app.yaml

# Optional: Common labels for all ArgoCD applications
commonLabels:
  managed-by: argocd
  project: n4k

