apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nirmata-kube-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/onboard-n4k-argo.git
    targetRevision: g-argo-v1.11.4
    path: nirmata-kube-controller
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nirmata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: otel-agent-config
    namespace: nirmata
    jsonPointers:
    - /data/config.yaml 
